### PR TITLE
cleanup run script and contracts

### PR DESCRIPTION
**Pull request by rinor**
- clean contract/Account abis to contain only what's needed from the service
- remove `build` from `start` script since heroku runs `build` script automatically

### CODE REVIEW

**Review by bartfish — APPROVED** [review]
Tested the branch locally and works well!

Vulnerabilities found by actions concern `mocha` (upgrading it to `9.2.0`) and `husky` (upgrading from `4.3.0` to `7.0.4`). Changes for `husky` [may require some changes in configs](https://github.com/typicode/husky#documentation), so not to break stuff now I propose that we fix packages in a separate PR.

**Comment by nicarq** [comment]
@bartfish curious are those upgrades really needed right now? Those dependencies are only available for testing

**Comment by bartfish** [comment]
@nicarq no, there's no priority for upgrading those packages right now. I just wanted to point out that the PR can be merged now (hence approval) and then we can take care of those vulnerabilities

**Comment by nicarq** [comment]
Okay 👍🏻

**Review by nicarq — APPROVED** [review]

**Pull request merged**
